// export const BASE_URL = "http://162.214.148.81:1337"
export const BASE_URL = "http://localhost:1337";
export const travellanda = "http://xmldemo.travellanda.com/xmlv1/";
export const travelName = "62576bb6fd2d1abe79ab734a48632213";
export const travelP = "QILkQE5dhk6A";
const holidayStand =
  "http://holidaystand.co.uk/api/get-pages.php?token=HolidayStand!2@3$%&pagename=";

export const about = holidayStand + "aboutus";
export const contact = holidayStand + "contact";
export const cookies = holidayStand + "cookies";
export const FAQ = holidayStand + "faq";
export const baggage = holidayStand + "baggagepolicies";
export const withInfant = holidayStand + "travelingwithinfants";
export const TandC = holidayStand + "terms";
export const refund = holidayStand + "purchasingrefunds";
export const privacy = holidayStand + "privacy";
export const assistance = holidayStand + "specialassistance";
export const specOffer =
  "http://holidaystand.co.uk/api/get-special-offers-page.php?token=HolidayStand!2@3$%";
export const holidayCountry =
  "http://holidaystand.co.uk/api/get-holiday-country.php?token=HolidayStand!2@3$%";
export const hotelPage =
  "http://holidaystand.co.uk/api/get-hotel-page.php?token=HolidayStand!2@3$%";
export const Home =
  "http://holidaystand.co.uk/api/get-home-page.php?token=HolidayStand!2@3$%";
export const FlightPage =
  "http://holidaystand.co.uk/api/get-flight-page.php?token=HolidayStand!2@3$%";
//export const destinationCom =
// "http://holidaystand.co.uk/api/get-holiday-country.php?token=HolidayStand!2@3$%";
export const holidayPackage =
  "http://holidaystand.co.uk/api/get-holiday-package.php?token=HolidayStand!2@3$%";
export const car =
  "http://holidaystand.co.uk/api/get-car-page.php?token=HolidayStand!2@3$%";
export const holidays =
  "http://holidaystand.co.uk/api/get-holidays-page.php?token=HolidayStand!2@3$%";
export const holidayTypes =
  "http://holidaystand.co.uk/api/get-holiday.php?token=HolidayStand!2@3$%";
